### ISSUE TITLE
Asset details share button does nothing

### ISSUE THREAD

**Issue by jmulq** [Vault-Hill/vhc-marketplace-app#116]
Steps to reproduce

- Nav to an asset details page
- Select share button
- Nothing happens

Low priority, can we hide until we implement this properly.

**Comment by creativogee** [comment]
@chandni-vault-hill  What should happen when user clicks on share is that a modal pops up displaying the asset link and a button to copy it to clipboard

**Comment by OTANatio** [comment]
Here https://www.figma.com/file/I1CfJiJLcSv19IcQyPY7Q0/VaultHill?node-id=7097%3A16970

@chandni-vault-hill
