### ISSUE TITLE
Design Wallet Connection

### ISSUE THREAD

**Issue by jmulq** [Vault-Hill/vhc-marketplace-app#18]

**Comment by jmulq** [comment]
Design review notes:
https://github.com/Vault-Hill/vhc-marketplace-app/issues/8

- Should only be for wallet connect and metamask
- What is a wallet - where will this link to? Do we scrap for MVP or link to external URL
- Connect wallet button required
- Address once connected should be displayed (see uniswap app for an example)
- User needs to be informed if they are on the wrong network - and potentially have the option to connect to the supported network (Polygon)
- User needs the ability to disconnect from the dapp https://www.dapp.com/dapps/

@OTANatio

**Comment by jmulq** [comment]
Design review notes 2:

- Profile icon should contain default ethereum wallet image
- Dropdown should contain address, balance of VHC, log out button (user settings to come later)

@OTANatio

**Comment by OTANatio** [comment]
Profile icon removed for MVP completed
Dropdown redesign completed ✅
